apiVersion: apps/v1
# управляет запуском подов и следит за состоянием
kind: Deployment
metadata:
  name: todo-deployment
spec:
  # сколько копий будет запущено 
  replicas: 1
  # какие поды сюда относятся
  selector:
    matchLabels:
      app: todo
  template:
    # метка, присваемая подам
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: frankiww/todo-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
# чтобы приложения могли общаться
kind: Service
metadata:
  name: todo-service
spec:
  # чтобы сервис был доступен снаружи 
  type: NodePort
  # поды, к которым проксируем трафик
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
